name: Rust CI for Moseiik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        
    steps:
  
        - name: Check out code
          uses: actions/checkout@v4 
          
        - name: Download assets/images
          run: |
            echo "Downloading assets/images..." 
            wget -q -O assets/moseiik_test_images.zip https://nasext-vaader.insa-rennes.fr/ietr-vaader/moseiik_test_images.zip
            echo "Extracting test images..."
            unzip -q assets/moseiik_test_images.zip -d assets/images
            echo "Images extracted to assets/images."
    
        #- name: Build
        #  run: |
        #    docker build --platform linux/${{ matrix.arch }} -t mosaiic:${{ matrix.arch }} . 
        
        - name: Build Docker image
          run: |
            docker buildx create --use 
            docker buildx build --no-cache --platform linux/${{ matrix.arch }} -t mosaiic:${{ matrix.arch }} . --load

        - name: Run tests
          run: |
            docker run --rm --platform linux/${{ matrix.arch }} mosaiic:${{ matrix.arch }} cargo test 
            
        #- name: Run
        #  run: |
        #    docker run --rm --platform linux/${{ matrix.arch }} mosaiic:${{ matrix.arch }} -it mosaiic
            
        - name: Clean up images
          run: |
            echo "Cleaning up assets/images..."
            rm -rf assets/images 

        - name: Cleanup Docker images
          run: |
            docker rmi mosaiic:${{ matrix.arch }}
          
