name: Rust CI for Moseiik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
  
        - name: Check out code
          uses: actions/checkout@v4 
          
        - name: Download assets/images
          run: |
            echo "Downloading assets/images..." 
            wget -q -O assets/moseiik_test_images.zip https://nasext-vaader.insa-rennes.fr/ietr-vaader/moseiik_test_images.zip
            echo "Extracting test images..."
            unzip -q assets/moseiik_test_images.zip -d assets/images
            echo "Images extracted to assets/images."
    
        - name: Build
          run: |
            docker build -t rustmosaic:v1 .
      
        - name: Run tests
          run: |
            docker run --rm rustmosaic:v1 cargo test --release
