name: Rust CI for Moseiik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
  
        - name: Check out code
          uses: actions/checkout@v4 
          
        - name: Download assets/images
          run: |
            echo "Downloading assets/images..."
            mkdir -p assets/images
            wget -q -P assets/images https://nasext-vaader.insa-rennes.fr/ietr-vaader/moseiik_test_images.zip
            unzip -q assets/images/images.zip -d assets/images
            echo "Assets downloaded."
    
        - name: Build
          run: |
            docker build -t rustmosaic:v1 .
      
        - name: Run tests
          run: |
            docker run --rm rustmosaic:v1 cargo test --release
