name: Rust CI for Moseiik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
  
        - name: Check out code
          uses: actions/checkout@v4
    
        - name: Build
          run: |
            docker build -t rustmosaic:v1 .
      
        - name: Run tests
          run: |
            docker run --rm rustmosaic:v1 cargo test --release
