name: Rust CI for Moseiik

on:
  push:
    branches: [ "update_dockerfile" ]
  pull_request:
    branches: [ "update_dockerfile" ]

jobs:
  test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          platform: [linux/amd64, linux/arm64]
        
      steps:
        
        - name: Check out code
          uses: actions/checkout@v4 

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: all

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Download assets/images
          run: |
            echo "Downloading assets/images..." 
            wget -q -O assets/moseiik_test_images.zip https://nasext-vaader.insa-rennes.fr/ietr-vaader/moseiik_test_images.zip
            echo "Extracting test images..."
            unzip -q assets/moseiik_test_images.zip -d assets/images
            echo "Images extracted to assets/images."
    
        - name: Build and Test
          run: |
            docker buildx build \
            --platform ${{ matrix.platform }} \
            -t moseiik:${{ matrix.platform }} \
            --load .
            docker run --rm moseiik:${{ matrix.platform }} cargo test --release
            
        - name: Clean up images
          run: |
            echo "Cleaning up assets/images..."
            rm -rf assets/images
            echo "Cleanup."
          
